version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: freelancer-postgres
    environment:
      POSTGRES_DB: freelancerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "#Cfyouvuid2"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - freelancer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service
  backend:
    build:
      context: ./freelancer-backend
      dockerfile: Dockerfile
    container_name: freelancer-backend
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/freelancerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "#Cfyouvuid2"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - freelancer-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: freelancer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - freelancer-network
    restart: unless-stopped

networks:
  freelancer-network:
    driver: bridge

volumes:
  postgres_data:



